# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: NTFmNGI1ZmJmM2Q4Y2FlYjEwZTExNTllMjJlMjYxODY0OGRlNmFjZjRiNmI1Y2IwMzZkMGM2OGEzOTc1MjE2YTI3MTM4ZmNmNjk2ZmVhMjYxNzg2NTlmMDgwYjdlMGYxYzI4MTI2N2I4MjhjMmViN2I4NTQ3ODU5YmUxZTVhMjI=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/
